### ISSUE TITLE
How to Update into the lastest respiratory

### ISSUE THREAD

**Issue by venturazz** [LanceRoe/h5p-selfhost-example#1]
Thank you so much for this template it is what I have been looking for so far. With very liitle knowledge about h5p I can host it in github finally. Currently, I am trying to update into the lastest version but it is not that simple. Could you probably update this template or share specific procedure to do so? Thank you in Advance

**Comment by LanceRoe** [comment]
Hi Venturazz,

I'm not positive about the issue you are having. I might recommend checking out the original source code from TunaPanda and reviewing one of their branches:
https://github.com/tunapanda/h5p-standalone/tree/master
